version: "3.8"
services:
  app:
    container_name: flask
    build: ./
    command: python ./templates/main.py
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - .:/templates